### ISSUE TITLE
update Github actions

### ISSUE THREAD

**Issue by vincentsarago** [developmentseed/geojson-pydantic#30]
https://github.com/developmentseed/geojson-pydantic/blob/744da3a7b9b68a531ea7e37a717325c5c96bda66/.github/workflows/ci.yml#L3

to

```
on:
  push:
    branches:
    - master
    tags:
    - '*'
  pull_request:
````

https://github.com/cogeotiff/rio-tiler/blob/master/.github/workflows/ci.yml#L4-L10
